---
- name: Install MySQL
  apt:
    name: mariadb-server
    state: present
    update_cache: yes

- name: Install Python MySQL module
  apt:
    name: python3-pymysql
    state: present

- name: Start and Enable MySQL
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Secure MySQL Installation (change root auth)
  become: yes
  shell: >
    mysql -u root --socket=/var/run/mysqld/mysqld.sock -p'{{ mysql_root_password }}' -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;" 
      
- name: Create WordPress Database
  mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "127.0.0.1"
    login_port: 3306

- name: Create WordPress User
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: "{{ mysql_db_name }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "127.0.0.1"
    login_port: 3306

- name: Configure MySQL for Remote Access
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: Restart MySQL
  service:
    name: mariadb
    state: restarted
